eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8771/eureka/
    fetch-registry: false
#  instance:
#    hostname: one url别名
server:
  port: 8772
spring:
  application:
    name: masterYang #serviceid

#redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 12345
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
#文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/test_redis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  resources:
    chain:
      strategy:
        content:
          enabled: true
    static-locations: classpath:/


#mapper文件配置
mybatis:
  mapper-locations: classpath:mapperXml/*.xml

#文件上传路径

